// Case studies, one per client/project. Rendered by the shared CaseStudy
// template (src/pages/CaseStudy.jsx) and routed at /work/:slug.
import {
  Globe, Star, Megaphone, Users, MessageSquare, TrendingUp, ShoppingCart,
  CreditCard, Truck, Package, LayoutDashboard, Search, Smartphone, Nfc,
  CalendarClock, UserPlus, FileText, BarChart2, Briefcase, Zap, Share2,
} from 'lucide-react'

export const CASE_STUDIES = {
  tapbywisein: {
    slug: 'tapbywisein',
    name: 'TapByWisein',
    image: '/clients/tapbywisein.png',
    tags: ['NFC Networking', 'SaaS Platform'],
    industry: 'Networking & Events',
    timeline: '10 weeks',
    stack: 'React · Supabase · Render',
    liveDomain: 'tapbywisein.com',
    liveUrl: 'https://www.tapbywisein.com/',
    heroTop: 'From paper cards',
    heroBottom: 'to a tap-to-connect network',
    intro: 'TapByWisein helps founders, professionals, and event attendees exchange details instantly with NFC-powered smart cards. We built the platform end to end — smart profiles, event networking, and a follow-up engine.',
    problemSub: 'Paper business cards get lost, and connections made at events rarely turn into relationships.',
    problems: [
      'Paper cards are forgotten, lost, or thrown away after events',
      'No easy way to share a full profile with one tap',
      'Contacts collected at events never get followed up',
      'Attendees had no way to find the right people to meet',
      'Organisers had no view of who connected with whom',
      'Details went stale the moment a job or number changed',
    ],
    solutionSub: 'A single NFC card and profile that turns every handshake into a saved, actionable connection.',
    solution: [
      { icon: Nfc,          title: 'NFC Smart Cards',     desc: 'Tap-to-share cards that open a live, always-up-to-date profile — no app needed.' },
      { icon: Smartphone,   title: 'Digital Profiles',    desc: 'Editable profiles with links, contact details, and a one-tap save-to-phone vCard.' },
      { icon: Users,        title: 'Who-to-Meet Feed',    desc: 'Event feed that surfaces the most relevant people for each attendee to connect with.' },
      { icon: CalendarClock,title: 'Events & Check-in',   desc: 'Event pages, attendee lists, and check-in so organisers see live engagement.' },
      { icon: Share2,       title: 'Instant Sharing',     desc: 'Share a profile by tap, QR, or link — the connection is saved for both sides.' },
      { icon: TrendingUp,   title: 'Follow-up Engine',    desc: 'Post-event nudges and duplicate detection so no promising lead slips away.' },
    ],
    resultsSub: 'Every tap now becomes a saved connection instead of a lost card.',
    results: [
      'Contacts exchanged in one tap, saved for both people',
      'Profiles stay current — update once, reflected everywhere',
      'Organisers get live visibility into event networking',
      'Attendees discover the right people to meet, faster',
      'Follow-ups actually happen instead of being forgotten',
      'A modern, memorable first impression at every meeting',
    ],
    ctaHeading: 'Building a platform of your own?',
    ctaSub: 'We take products from idea to launch — and run them after. Let’s talk.',
  },

  'unisys-infotech': {
    slug: 'unisys-infotech',
    name: 'Unisys Infotech',
    image: '/clients/unisysinfotech.png',
    tags: ['IT Services', 'Corporate Website'],
    industry: 'IT Solutions & Services',
    timeline: '4 weeks',
    stack: 'React · Tailwind · Node.js',
    liveDomain: 'unisysinfotech.com',
    liveUrl: 'https://www.unisysinfotech.com/',
    heroTop: 'A credible online home',
    heroBottom: 'for an IT services company',
    intro: 'Unisys Infotech offers IT outsourcing and professional services but had no online presence to match. We built a modern corporate website that positions them as a serious, enterprise-ready partner.',
    problemSub: 'A capable services firm that looked invisible and dated online.',
    problems: [
      'No website to present services, expertise, or credibility',
      'Prospects had no way to evaluate the company online',
      'No careers page to attract and collect candidate applications',
      'Enquiries relied entirely on referrals and cold outreach',
      'Brand looked smaller and less established than it is',
      'No clear structure to explain the range of services offered',
    ],
    solutionSub: 'A polished, structured website that communicates scale and expertise.',
    solution: [
      { icon: Globe,          title: 'Corporate Website',   desc: 'A clean, professional site presenting the company, services, and value clearly.' },
      { icon: Briefcase,      title: 'Services Pages',      desc: 'Dedicated pages for IT outsourcing, professional services, and consulting.' },
      { icon: Users,          title: 'Careers & About',     desc: 'Company story, team, and a careers page to attract talent.' },
      { icon: MessageSquare,  title: 'Lead Capture',        desc: 'Contact forms and clear CTAs so enquiries flow in from the site.' },
      { icon: Search,         title: 'SEO Foundation',      desc: 'On-page SEO so the company ranks for its core service searches.' },
      { icon: Smartphone,     title: 'Responsive Design',   desc: 'A fast, mobile-first experience that looks sharp on every device.' },
    ],
    resultsSub: 'A web presence that finally matches the quality of the work.',
    results: [
      'A credible, enterprise-ready online presence',
      'Prospects can evaluate services before reaching out',
      'Inbound enquiries now come through the website',
      'Careers page collects applications directly',
      'Stronger, more consistent brand across every page',
      'Discoverable on search for core service terms',
    ],
    ctaHeading: 'Need a site that earns trust?',
    ctaSub: 'We build fast, credible websites that turn visitors into enquiries.',
  },

  'jobly-solutions': {
    slug: 'jobly-solutions',
    name: 'Jobly Solutions',
    image: '/clients/joblysolutions.png',
    tags: ['Staffing & Consulting', 'Website'],
    industry: 'Recruitment & Staffing',
    timeline: '5 weeks',
    stack: 'React · Tailwind · Node.js',
    liveDomain: 'joblysolutions.com',
    liveUrl: 'https://www.joblysolutions.com/',
    heroTop: 'A staffing brand',
    heroBottom: 'built to win clients',
    intro: 'Jobly Solutions provides IT consulting and staffing services. We built a website that presents their staffing and consulting offering clearly and turns visitors into qualified leads.',
    problemSub: 'A staffing firm competing for enterprise clients without a modern web presence.',
    problems: [
      'No professional website to present staffing services',
      'Hard to appear credible next to larger competitors',
      'No structured way to show industries and roles served',
      'Client and candidate enquiries handled entirely manually',
      'No online funnel to capture and qualify leads',
      'Limited visibility in search for staffing services',
    ],
    solutionSub: 'A conversion-focused website tailored to staffing and consulting.',
    solution: [
      { icon: Globe,          title: 'Staffing Website',    desc: 'A professional site presenting consulting and staffing services clearly.' },
      { icon: Briefcase,      title: 'Services & Industries',desc: 'Pages for IT consulting, staffing, and the industries served.' },
      { icon: UserPlus,       title: 'Client & Candidate CTAs', desc: 'Separate paths for clients hiring and candidates applying.' },
      { icon: MessageSquare,  title: 'Lead Capture Forms',  desc: 'Enquiry forms that route straight to the team.' },
      { icon: Search,         title: 'SEO Foundation',      desc: 'On-page SEO to rank for consulting and staffing searches.' },
      { icon: Smartphone,     title: 'Responsive Design',   desc: 'A polished experience across desktop and mobile.' },
    ],
    resultsSub: 'A website that works as the firm’s always-on sales team.',
    results: [
      'A credible, modern presence to win enterprise trust',
      'Clear separation of client and candidate journeys',
      'Inbound leads captured and qualified through the site',
      'Services and industries presented professionally',
      'Improved visibility for staffing-related searches',
      'A brand that competes with much larger firms',
    ],
    ctaHeading: 'Want a site that brings in leads?',
    ctaSub: 'We design websites that turn traffic into qualified enquiries.',
  },

  'media-manager': {
    slug: 'media-manager',
    name: 'Media Manager 4U',
    image: '/clients/mediamanager4u.png',
    tags: ['Personal Branding', 'Marketing Site'],
    industry: 'Media & Marketing',
    timeline: '6 weeks',
    stack: 'React · Tailwind · Node.js',
    liveDomain: 'mediamanager4u.com',
    liveUrl: 'https://www.mediamanager4u.com/#/',
    heroTop: 'Turning founders',
    heroBottom: 'into industry authorities',
    intro: 'Media Manager 4U builds personal brands for founders that speak, connect, and convert. We built the marketing site that packages their offer and books strategy calls.',
    problemSub: 'A proven service with no website to capture the demand it was generating.',
    problems: [
      'No website to present the personal-branding offer',
      'Results and social proof lived only in DMs and decks',
      'No clear funnel to book strategy calls',
      'Prospects had no single place to understand the service',
      'Hard to convey authority without a polished web presence',
      'Enquiries depended on outreach instead of inbound',
    ],
    solutionSub: 'A high-converting marketing site built around booking calls.',
    solution: [
      { icon: Globe,          title: 'Marketing Website',   desc: 'A punchy site that frames the offer and drives strategy-call bookings.' },
      { icon: BarChart2,      title: 'Results & Proof',     desc: 'Stats, case results, and client logos front and centre to build trust.' },
      { icon: Megaphone,      title: 'Services Pages',      desc: 'Clear breakdown of the personal-branding services on offer.' },
      { icon: CalendarClock,  title: 'Call Booking',        desc: 'Frictionless “book a free strategy call” flow throughout the site.' },
      { icon: Star,           title: 'Social Proof',        desc: 'Testimonials and trusted-by logos to convert cold visitors.' },
      { icon: Search,         title: 'SEO Foundation',      desc: 'On-page SEO so the brand shows up for its niche searches.' },
    ],
    resultsSub: 'A website that finally sells the service as well as the service delivers.',
    results: [
      'A clear, high-converting home for the offer',
      'Social proof and results presented up front',
      'Strategy calls booked directly from the site',
      'Stronger authority and first impression',
      'Inbound enquiries instead of pure outreach',
      'A brand presence founders trust on arrival',
    ],
    ctaHeading: 'Sitting on demand with no funnel?',
    ctaSub: 'We build sites that turn attention into booked calls.',
  },

  'rolex-ads': {
    slug: 'rolex-ads',
    name: 'Rolex Ads',
    image: '/clients/rolexads.png',
    tags: ['Marketing Agency', 'Online Visibility'],
    industry: 'Marketing & Advertising',
    timeline: '5 weeks',
    stack: 'React · Tailwind · Node.js',
    liveDomain: 'rolexads.in',
    liveUrl: 'https://www.rolexads.in/',
    heroTop: 'From WhatsApp DMs',
    heroBottom: 'to 4x more leads',
    intro: 'Rolex Ads was a growing marketing agency running entirely on WhatsApp referrals — no website, no online presence. We built them a professional agency site that now generates 4x the leads they had before.',
    problemSub: 'A capable agency invisible to anyone who didn’t already know them personally.',
    problems: [
      'No website — the entire business ran through WhatsApp',
      'Potential clients had no way to discover the agency online',
      'No portfolio to showcase past campaigns and results',
      'Every lead came through personal referrals only',
      'Hard to appear credible without a web presence',
      'Lost clients to competitors with polished agency sites',
    ],
    solutionSub: 'A full agency website built to convert visitors into enquiries.',
    solution: [
      { icon: Globe,          title: 'Agency Website',     desc: 'A clean, professional website showcasing services, portfolio, and story.' },
      { icon: Star,           title: 'Portfolio Showcase', desc: 'Gallery of past campaigns and client results to build credibility.' },
      { icon: Megaphone,      title: 'Services Pages',     desc: 'Dedicated pages for ads, branding, social media, and SEO.' },
      { icon: Users,          title: 'About & Team',       desc: 'Agency story and team profiles to build trust with prospects.' },
      { icon: MessageSquare,  title: 'Lead Capture',       desc: 'Contact form and WhatsApp CTA so enquiries flow in automatically.' },
      { icon: Search,         title: 'SEO Foundation',     desc: 'On-page SEO so the agency ranks for local marketing searches.' },
    ],
    resultsSub: 'The website became the agency’s best-performing sales tool.',
    results: [
      'Leads increased 4x within months of launch',
      'Clients now find Rolex Ads on Google — no referral needed',
      'Portfolio gives instant credibility to cold prospects',
      'WhatsApp enquiries now come from the website',
      'Professional presence opened doors to larger clients',
      'Visible across search, social shares, and direct visits',
    ],
    ctaHeading: 'Running on referrals only?',
    ctaSub: 'Let us build you a website that works as your 24/7 salesperson.',
  },

  'nivi-collections': {
    slug: 'nivi-collections',
    name: 'Nivi Collections',
    image: '/clients/nivicollections.png',
    tags: ['E-Commerce', 'Fashion'],
    industry: 'Fashion & Retail',
    timeline: '5 weeks',
    stack: 'Shopify · Liquid · Custom Theme',
    liveDomain: 'nivicollections.com',
    liveUrl: 'https://www.nivicollections.com/',
    heroTop: 'From offline sales',
    heroBottom: 'to a pan-India store',
    intro: 'Nivi Collections is a saree and ethnic-wear brand that sold mostly offline and over WhatsApp. We built an elegant online store that sells nationwide with payments and delivery built in.',
    problemSub: 'A beautiful collection that customers outside the city couldn’t buy.',
    problems: [
      'Sales limited to walk-ins and WhatsApp messages',
      'No online catalogue for customers to browse collections',
      'Manual order-taking and payment collection',
      'No way to reach customers across India',
      'Product photos scattered across chats and posts',
      'No trusted checkout to convert interested buyers',
    ],
    solutionSub: 'A premium online store built to browse, trust, and buy.',
    solution: [
      { icon: ShoppingCart,   title: 'Online Store',       desc: 'An elegant storefront to browse sarees and collections by category.' },
      { icon: Package,        title: 'Product Catalogue',  desc: 'Rich product pages with imagery, variants, and descriptions.' },
      { icon: CreditCard,     title: 'Secure Payments',    desc: 'Integrated checkout with trusted online payment options.' },
      { icon: Truck,          title: 'Pan-India Delivery', desc: 'Shipping and order management set up for nationwide delivery.' },
      { icon: LayoutDashboard,title: 'Admin & Inventory',  desc: 'Simple back-office to manage products, orders, and stock.' },
      { icon: Zap,            title: 'Fast, Mobile-first', desc: 'A quick, mobile-friendly experience that converts browsers to buyers.' },
    ],
    resultsSub: 'The collection is now open for business, everywhere.',
    results: [
      'Customers can browse and buy online, 24/7',
      'Orders and payments handled automatically',
      'Reach extended to customers across India',
      'A premium brand experience that builds trust',
      'Product catalogue organised and always current',
      'A scalable base to grow the store further',
    ],
    ctaHeading: 'Ready to sell online?',
    ctaSub: 'We build stores that turn browsers into buyers, nationwide.',
  },
}

// Ordered list for any index/listing use.
export const CASE_STUDY_LIST = [
  'tapbywisein', 'unisys-infotech', 'jobly-solutions',
  'media-manager', 'rolex-ads', 'nivi-collections',
].map((slug) => CASE_STUDIES[slug])
