// Project templates shown on the New Project page and the dashboard picker.
// Data only (icons are lucide component refs); creation logic lives in NewProject.
import { Square, Rocket, Globe, Megaphone, Map, BookOpen, TrendingUp, UserPlus, PenTool, Bug, Users, ClipboardCheck, Calendar, CalendarCheck, Target, PieChart, Search, Layers, Server, Palette, Flag, ClipboardList, Video, Mic, FileText, Award, Plane, Shield, Receipt, BarChart, LifeBuoy, HelpCircle, MessageSquare, GraduationCap, Presentation, CheckSquare, Home, Compass, Dumbbell, Briefcase, Newspaper, Gift, Database, Store, Mail, Share2, Star, Wrench, DollarSign, Camera, Repeat, UserCheck, Wallet, Building2, Scale, ListChecks, Clock, Heart, Zap, Lightbulb, Building } from 'lucide-react'

export const TEMPLATES = [
  {
    key: 'blank',
    Icon: Square,
    name: 'Blank',
    tasks: [],
    milestones: [],
  },
  {
    key: 'startup',
    category: 'Business & Sales',
    Icon: Rocket,
    name: 'Startup Launch',
    description: '12 tasks · 4 milestones',
    tasks: [
      { title: 'Define MVP features and scope', status: 'todo', priority: 'high' },
      { title: 'Set up development environment', status: 'todo', priority: 'medium' },
      { title: 'Design wireframes and user flows', status: 'todo', priority: 'high' },
      { title: 'Build core product features', status: 'todo', priority: 'high' },
      { title: 'Set up landing page', status: 'todo', priority: 'medium' },
      { title: 'Integrate payment gateway', status: 'todo', priority: 'high' },
      { title: 'Write onboarding copy', status: 'todo', priority: 'medium' },
      { title: 'Set up analytics tracking', status: 'todo', priority: 'low' },
      { title: 'Beta test with 10 users', status: 'todo', priority: 'high' },
      { title: 'Fix bugs from beta feedback', status: 'todo', priority: 'urgent' },
      { title: 'Set up customer support channel', status: 'todo', priority: 'medium' },
      { title: 'Prepare launch announcement', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Wireframes approved', daysFromNow: 7 },
      { title: 'MVP feature complete', daysFromNow: 21 },
      { title: 'Beta launch', daysFromNow: 35 },
      { title: 'Public launch', daysFromNow: 45 },
    ],
  },
  {
    key: 'webdev',
    category: 'Design & Engineering',
    Icon: Globe,
    name: 'Web Development',
    description: '14 tasks · 5 milestones',
    tasks: [
      { title: 'Gather requirements from client', status: 'todo', priority: 'high' },
      { title: 'Create sitemap and architecture', status: 'todo', priority: 'high' },
      { title: 'Design UI mockups', status: 'todo', priority: 'high' },
      { title: 'Get design approval', status: 'todo', priority: 'medium' },
      { title: 'Set up project repository', status: 'todo', priority: 'medium' },
      { title: 'Build homepage', status: 'todo', priority: 'high' },
      { title: 'Build inner pages', status: 'todo', priority: 'high' },
      { title: 'Add animations and interactions', status: 'todo', priority: 'medium' },
      { title: 'Integrate CMS or backend', status: 'todo', priority: 'medium' },
      { title: 'Cross-browser and mobile testing', status: 'todo', priority: 'high' },
      { title: 'SEO setup and meta tags', status: 'todo', priority: 'medium' },
      { title: 'Performance optimization', status: 'todo', priority: 'medium' },
      { title: 'Client review round', status: 'todo', priority: 'high' },
      { title: 'Deploy to production', status: 'todo', priority: 'urgent' },
    ],
    milestones: [
      { title: 'Design approved', daysFromNow: 5 },
      { title: 'Homepage done', daysFromNow: 14 },
      { title: 'All pages complete', daysFromNow: 25 },
      { title: 'Client review done', daysFromNow: 32 },
      { title: 'Site live', daysFromNow: 38 },
    ],
  },
  {
    key: 'marketing',
    category: 'Business & Sales',
    Icon: Megaphone,
    name: 'Marketing Campaign',
    description: '10 tasks · 3 milestones',
    tasks: [
      { title: 'Define campaign goals and KPIs', status: 'todo', priority: 'high' },
      { title: 'Identify target audience', status: 'todo', priority: 'high' },
      { title: 'Create campaign messaging and hooks', status: 'todo', priority: 'high' },
      { title: 'Design ad creatives', status: 'todo', priority: 'medium' },
      { title: 'Write ad copy for all channels', status: 'todo', priority: 'medium' },
      { title: 'Set up ad campaigns (Meta/Google)', status: 'todo', priority: 'high' },
      { title: 'Launch email sequence', status: 'todo', priority: 'medium' },
      { title: 'Monitor and optimize ads daily', status: 'todo', priority: 'urgent' },
      { title: 'A/B test creatives', status: 'todo', priority: 'medium' },
      { title: 'Final performance report', status: 'todo', priority: 'low' },
    ],
    milestones: [
      { title: 'Campaign assets ready', daysFromNow: 7 },
      { title: 'Campaign goes live', daysFromNow: 10 },
      { title: 'Performance review', daysFromNow: 30 },
    ],
  },
  {
    key: 'roadmap',
    category: 'Design & Engineering',
    Icon: Map,
    name: 'Product Roadmap',
    description: '12 tasks · 5 milestones',
    tasks: [
      { title: 'Collect customer feedback and pain points', status: 'todo', priority: 'high' },
      { title: 'Prioritize features using impact/effort matrix', status: 'todo', priority: 'high' },
      { title: 'Define Q1 goals', status: 'todo', priority: 'high' },
      { title: 'Write product specs for top features', status: 'todo', priority: 'medium' },
      { title: 'Validate concepts with users', status: 'todo', priority: 'medium' },
      { title: 'Build feature A', status: 'todo', priority: 'high' },
      { title: 'Build feature B', status: 'todo', priority: 'high' },
      { title: 'Build feature C', status: 'todo', priority: 'medium' },
      { title: 'Internal QA testing', status: 'todo', priority: 'high' },
      { title: 'Staged rollout to users', status: 'todo', priority: 'medium' },
      { title: 'Monitor metrics post-launch', status: 'todo', priority: 'medium' },
      { title: 'Plan Q2 roadmap', status: 'todo', priority: 'low' },
    ],
    milestones: [
      { title: 'Roadmap finalized', daysFromNow: 7 },
      { title: 'Feature A shipped', daysFromNow: 21 },
      { title: 'Feature B shipped', daysFromNow: 35 },
      { title: 'Feature C shipped', daysFromNow: 50 },
      { title: 'Q1 review complete', daysFromNow: 60 },
    ],
  },
  {
    key: 'course',
    category: 'Personal & Productivity',
    Icon: BookOpen,
    name: 'Personal Course',
    description: '8 tasks · 3 milestones',
    tasks: [
      { title: 'Define course topic and target student', status: 'todo', priority: 'high' },
      { title: 'Outline curriculum and modules', status: 'todo', priority: 'high' },
      { title: 'Record module 1 videos', status: 'todo', priority: 'high' },
      { title: 'Record module 2 videos', status: 'todo', priority: 'high' },
      { title: 'Record module 3 videos', status: 'todo', priority: 'high' },
      { title: 'Edit and export videos', status: 'todo', priority: 'medium' },
      { title: 'Set up course on platform', status: 'todo', priority: 'medium' },
      { title: 'Launch to first students', status: 'todo', priority: 'urgent' },
    ],
    milestones: [
      { title: 'Curriculum approved', daysFromNow: 5 },
      { title: 'All videos recorded', daysFromNow: 20 },
      { title: 'Course live', daysFromNow: 30 },
    ],
  },

  // ── Business & Sales ──────────────────────────────────────
  {
    key: 'sales-pipeline',
    category: 'Business & Sales',
    Icon: TrendingUp,
    name: 'Sales Pipeline',
    description: '8 tasks · 3 milestones',
    tasks: [
      { title: 'Build target account and lead list', status: 'todo', priority: 'high' },
      { title: 'Write cold outreach templates', status: 'todo', priority: 'high' },
      { title: 'Send first outreach batch', status: 'todo', priority: 'high' },
      { title: 'Book discovery calls', status: 'todo', priority: 'high' },
      { title: 'Send proposals to qualified leads', status: 'todo', priority: 'urgent' },
      { title: 'Follow up on open proposals', status: 'todo', priority: 'high' },
      { title: 'Negotiate and close deals', status: 'todo', priority: 'urgent' },
      { title: 'Hand off won deals to delivery', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Lead list ready', daysFromNow: 3 },
      { title: 'First proposals sent', daysFromNow: 14 },
      { title: 'First deal closed', daysFromNow: 30 },
    ],
  },
  {
    key: 'client-onboarding',
    category: 'Business & Sales',
    Icon: UserPlus,
    name: 'Client Onboarding',
    description: '8 tasks · 3 milestones',
    tasks: [
      { title: 'Send welcome email and contract', status: 'todo', priority: 'high' },
      { title: 'Collect brand assets and access', status: 'todo', priority: 'high' },
      { title: 'Schedule kickoff call', status: 'todo', priority: 'high' },
      { title: 'Document goals and success metrics', status: 'todo', priority: 'high' },
      { title: 'Set up shared workspace and channels', status: 'todo', priority: 'medium' },
      { title: 'Agree on timeline and milestones', status: 'todo', priority: 'high' },
      { title: 'Send first status update', status: 'todo', priority: 'medium' },
      { title: 'Confirm invoicing and billing details', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Contract signed', daysFromNow: 3 },
      { title: 'Kickoff complete', daysFromNow: 7 },
      { title: 'Onboarding complete', daysFromNow: 14 },
    ],
  },

  // ── Design & Engineering ──────────────────────────────────
  {
    key: 'design-sprint',
    category: 'Design & Engineering',
    Icon: PenTool,
    name: 'Design Sprint',
    description: '8 tasks · 3 milestones',
    tasks: [
      { title: 'Map the problem and pick a target', status: 'todo', priority: 'high' },
      { title: 'Gather lightning demos and inspiration', status: 'todo', priority: 'medium' },
      { title: 'Sketch competing solutions', status: 'todo', priority: 'high' },
      { title: 'Decide on the strongest concept', status: 'todo', priority: 'high' },
      { title: 'Build a clickable prototype', status: 'todo', priority: 'high' },
      { title: 'Recruit 5 test users', status: 'todo', priority: 'medium' },
      { title: 'Run usability tests', status: 'todo', priority: 'high' },
      { title: 'Synthesize findings and next steps', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Concept decided', daysFromNow: 2 },
      { title: 'Prototype ready', daysFromNow: 4 },
      { title: 'Test results in', daysFromNow: 5 },
    ],
  },
  {
    key: 'bug-tracker',
    category: 'Design & Engineering',
    Icon: Bug,
    name: 'Bug Tracker / Sprint',
    description: '8 tasks · 2 milestones',
    tasks: [
      { title: 'Triage incoming bug reports', status: 'todo', priority: 'high' },
      { title: 'Reproduce and confirm top bugs', status: 'todo', priority: 'high' },
      { title: 'Prioritize by severity and impact', status: 'todo', priority: 'high' },
      { title: 'Fix critical / blocker bugs', status: 'todo', priority: 'urgent' },
      { title: 'Fix high-priority bugs', status: 'todo', priority: 'high' },
      { title: 'Write regression tests', status: 'todo', priority: 'medium' },
      { title: 'Code review and QA pass', status: 'todo', priority: 'high' },
      { title: 'Deploy fixes and verify in prod', status: 'todo', priority: 'urgent' },
    ],
    milestones: [
      { title: 'Backlog triaged', daysFromNow: 2 },
      { title: 'Sprint bugs cleared', daysFromNow: 14 },
    ],
  },

  // ── HR & Operations ───────────────────────────────────────
  {
    key: 'hiring',
    category: 'HR & Operations',
    Icon: Users,
    name: 'Hiring Pipeline',
    description: '9 tasks · 3 milestones',
    tasks: [
      { title: 'Write the job description', status: 'todo', priority: 'high' },
      { title: 'Post to job boards and network', status: 'todo', priority: 'high' },
      { title: 'Screen incoming applications', status: 'todo', priority: 'high' },
      { title: 'Run phone screens', status: 'todo', priority: 'high' },
      { title: 'Send take-home / skills assessment', status: 'todo', priority: 'medium' },
      { title: 'Conduct on-site / final interviews', status: 'todo', priority: 'high' },
      { title: 'Check references', status: 'todo', priority: 'medium' },
      { title: 'Make offer and negotiate', status: 'todo', priority: 'urgent' },
      { title: 'Close role and notify candidates', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Role posted', daysFromNow: 2 },
      { title: 'Shortlist ready', daysFromNow: 14 },
      { title: 'Offer accepted', daysFromNow: 30 },
    ],
  },
  {
    key: 'employee-onboarding',
    category: 'HR & Operations',
    Icon: ClipboardCheck,
    name: 'Employee Onboarding',
    description: '8 tasks · 2 milestones',
    tasks: [
      { title: 'Prepare offer letter and paperwork', status: 'todo', priority: 'high' },
      { title: 'Set up accounts, email, and tools', status: 'todo', priority: 'high' },
      { title: 'Ship equipment / laptop', status: 'todo', priority: 'high' },
      { title: 'Assign an onboarding buddy', status: 'todo', priority: 'medium' },
      { title: 'Schedule week-1 intro meetings', status: 'todo', priority: 'medium' },
      { title: 'Share handbook and policies', status: 'todo', priority: 'medium' },
      { title: 'Set 30/60/90 day goals', status: 'todo', priority: 'high' },
      { title: 'First-week check-in', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Day 1 ready', daysFromNow: 5 },
      { title: '30-day check-in', daysFromNow: 30 },
    ],
  },
  {
    key: 'event-planning',
    category: 'HR & Operations',
    Icon: Calendar,
    name: 'Event Planning',
    description: '9 tasks · 3 milestones',
    tasks: [
      { title: 'Define event goals and budget', status: 'todo', priority: 'high' },
      { title: 'Pick date and book venue', status: 'todo', priority: 'high' },
      { title: 'Confirm speakers / agenda', status: 'todo', priority: 'high' },
      { title: 'Arrange catering and logistics', status: 'todo', priority: 'medium' },
      { title: 'Build registration page', status: 'todo', priority: 'medium' },
      { title: 'Promote the event', status: 'todo', priority: 'high' },
      { title: 'Prepare signage and materials', status: 'todo', priority: 'medium' },
      { title: 'Run the event', status: 'todo', priority: 'urgent' },
      { title: 'Send thank-you and collect feedback', status: 'todo', priority: 'low' },
    ],
    milestones: [
      { title: 'Venue booked', daysFromNow: 7 },
      { title: 'Registration open', daysFromNow: 21 },
      { title: 'Event day', daysFromNow: 45 },
    ],
  },

  // ── Personal & Productivity ───────────────────────────────
  {
    key: 'weekly-planner',
    category: 'Personal & Productivity',
    Icon: CalendarCheck,
    name: 'Weekly Planner',
    description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Review last week and open items', status: 'todo', priority: 'medium' },
      { title: 'Set top 3 priorities for the week', status: 'todo', priority: 'high' },
      { title: 'Block deep-work time on calendar', status: 'todo', priority: 'high' },
      { title: 'Plan errands and admin', status: 'todo', priority: 'low' },
      { title: 'Schedule exercise and breaks', status: 'todo', priority: 'medium' },
      { title: 'Prep for key meetings', status: 'todo', priority: 'medium' },
      { title: 'Friday review and reset', status: 'todo', priority: 'medium' },
    ],
    milestones: [
      { title: 'Week planned', daysFromNow: 1 },
      { title: 'Week reviewed', daysFromNow: 7 },
    ],
  },
  {
    key: 'goal-tracker',
    category: 'Personal & Productivity',
    Icon: Target,
    name: 'Goal Tracker',
    description: '7 tasks · 3 milestones',
    tasks: [
      { title: 'Write down the goal and why it matters', status: 'todo', priority: 'high' },
      { title: 'Break it into monthly targets', status: 'todo', priority: 'high' },
      { title: 'Define this week’s action steps', status: 'todo', priority: 'high' },
      { title: 'Set up a daily habit / streak', status: 'todo', priority: 'medium' },
      { title: 'Track progress weekly', status: 'todo', priority: 'medium' },
      { title: 'Adjust plan based on what’s working', status: 'todo', priority: 'medium' },
      { title: 'Reward hitting the milestone', status: 'todo', priority: 'low' },
    ],
    milestones: [
      { title: 'Plan set', daysFromNow: 2 },
      { title: 'Month 1 target', daysFromNow: 30 },
      { title: 'Goal reached', daysFromNow: 90 },
    ],
  },

  // ── Business & Sales (more) ───────────────────────────────
  {
    key: 'account-outreach', category: 'Business & Sales', Icon: Target, name: 'Account-Based Outreach', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Pick 20 dream accounts', status: 'todo', priority: 'high' },
      { title: 'Map decision-makers per account', status: 'todo', priority: 'high' },
      { title: 'Research each account’s pain points', status: 'todo', priority: 'medium' },
      { title: 'Write personalized outreach per account', status: 'todo', priority: 'high' },
      { title: 'Run multi-touch sequence (email + LinkedIn)', status: 'todo', priority: 'high' },
      { title: 'Book intro meetings', status: 'todo', priority: 'urgent' },
      { title: 'Log outcomes and next steps', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Account list locked', daysFromNow: 3 }, { title: 'First meetings booked', daysFromNow: 21 } ],
  },
  {
    key: 'partnership-deal', category: 'Business & Sales', Icon: Briefcase, name: 'Partnership Deal', description: '7 tasks · 3 milestones',
    tasks: [
      { title: 'Shortlist potential partners', status: 'todo', priority: 'high' },
      { title: 'Draft partnership proposal', status: 'todo', priority: 'high' },
      { title: 'Pitch to partner stakeholders', status: 'todo', priority: 'high' },
      { title: 'Align on terms and revenue split', status: 'todo', priority: 'high' },
      { title: 'Legal review of agreement', status: 'todo', priority: 'medium' },
      { title: 'Sign and announce partnership', status: 'todo', priority: 'urgent' },
      { title: 'Plan joint go-to-market', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Proposal sent', daysFromNow: 7 }, { title: 'Terms agreed', daysFromNow: 21 }, { title: 'Deal signed', daysFromNow: 35 } ],
  },
  {
    key: 'qbr', category: 'Business & Sales', Icon: PieChart, name: 'Quarterly Business Review', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pull quarter’s metrics and revenue', status: 'todo', priority: 'high' },
      { title: 'Compare vs targets and last quarter', status: 'todo', priority: 'high' },
      { title: 'Gather wins, losses, and lessons', status: 'todo', priority: 'medium' },
      { title: 'Build the QBR deck', status: 'todo', priority: 'high' },
      { title: 'Set next-quarter goals', status: 'todo', priority: 'high' },
      { title: 'Present to leadership / client', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Data compiled', daysFromNow: 5 }, { title: 'QBR presented', daysFromNow: 10 } ],
  },

  // ── Marketing ─────────────────────────────────────────────
  {
    key: 'content-calendar', category: 'Marketing', Icon: Calendar, name: 'Content Calendar', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Define monthly content themes', status: 'todo', priority: 'high' },
      { title: 'Brainstorm 20 post ideas', status: 'todo', priority: 'high' },
      { title: 'Assign owners and due dates', status: 'todo', priority: 'medium' },
      { title: 'Draft posts for week 1', status: 'todo', priority: 'high' },
      { title: 'Design accompanying graphics', status: 'todo', priority: 'medium' },
      { title: 'Schedule posts', status: 'todo', priority: 'medium' },
      { title: 'Review engagement and iterate', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Calendar filled', daysFromNow: 5 }, { title: 'Month published', daysFromNow: 30 } ],
  },
  {
    key: 'product-launch-mktg', category: 'Marketing', Icon: Rocket, name: 'Product Launch (GTM)', description: '8 tasks · 3 milestones',
    tasks: [
      { title: 'Define positioning and messaging', status: 'todo', priority: 'high' },
      { title: 'Build launch landing page', status: 'todo', priority: 'high' },
      { title: 'Prepare press kit and assets', status: 'todo', priority: 'medium' },
      { title: 'Line up launch-day partners/influencers', status: 'todo', priority: 'medium' },
      { title: 'Write launch email + social posts', status: 'todo', priority: 'high' },
      { title: 'Schedule Product Hunt / launch post', status: 'todo', priority: 'high' },
      { title: 'Go live and monitor', status: 'todo', priority: 'urgent' },
      { title: 'Post-launch recap and metrics', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Assets ready', daysFromNow: 10 }, { title: 'Launch day', daysFromNow: 14 }, { title: 'Recap done', daysFromNow: 21 } ],
  },
  {
    key: 'seo-campaign', category: 'Marketing', Icon: Search, name: 'SEO Campaign', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Run keyword research', status: 'todo', priority: 'high' },
      { title: 'Audit current site + fix issues', status: 'todo', priority: 'high' },
      { title: 'Map keywords to pages', status: 'todo', priority: 'medium' },
      { title: 'Write / optimize target pages', status: 'todo', priority: 'high' },
      { title: 'Build internal links', status: 'todo', priority: 'medium' },
      { title: 'Earn backlinks / outreach', status: 'todo', priority: 'medium' },
      { title: 'Track rankings monthly', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Audit complete', daysFromNow: 7 }, { title: 'Pages optimized', daysFromNow: 30 } ],
  },

  // ── Design & Engineering (more) ───────────────────────────
  {
    key: 'mobile-app', category: 'Design & Engineering', Icon: Layers, name: 'Mobile App Build', description: '9 tasks · 4 milestones',
    tasks: [
      { title: 'Define app scope and platforms', status: 'todo', priority: 'high' },
      { title: 'Design app screens and flows', status: 'todo', priority: 'high' },
      { title: 'Set up project and CI', status: 'todo', priority: 'medium' },
      { title: 'Build authentication', status: 'todo', priority: 'high' },
      { title: 'Build core screens', status: 'todo', priority: 'high' },
      { title: 'Integrate push notifications', status: 'todo', priority: 'medium' },
      { title: 'QA on real devices', status: 'todo', priority: 'high' },
      { title: 'Prepare store listings', status: 'todo', priority: 'medium' },
      { title: 'Submit to App Store / Play Store', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Designs done', daysFromNow: 10 }, { title: 'Auth + core built', daysFromNow: 30 }, { title: 'Beta ready', daysFromNow: 45 }, { title: 'Live in stores', daysFromNow: 60 } ],
  },
  {
    key: 'api-integration', category: 'Design & Engineering', Icon: Server, name: 'API Integration', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Read the API docs and auth model', status: 'todo', priority: 'high' },
      { title: 'Get API keys / sandbox access', status: 'todo', priority: 'high' },
      { title: 'Build the integration layer', status: 'todo', priority: 'high' },
      { title: 'Handle errors, retries, and rate limits', status: 'todo', priority: 'high' },
      { title: 'Write tests against sandbox', status: 'todo', priority: 'medium' },
      { title: 'Deploy and monitor in prod', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Sandbox working', daysFromNow: 7 }, { title: 'Live in prod', daysFromNow: 18 } ],
  },
  {
    key: 'design-system', category: 'Design & Engineering', Icon: Palette, name: 'Design System', description: '7 tasks · 3 milestones',
    tasks: [
      { title: 'Audit existing UI patterns', status: 'todo', priority: 'high' },
      { title: 'Define tokens (color, type, spacing)', status: 'todo', priority: 'high' },
      { title: 'Build core components', status: 'todo', priority: 'high' },
      { title: 'Document usage guidelines', status: 'todo', priority: 'medium' },
      { title: 'Publish component library', status: 'todo', priority: 'medium' },
      { title: 'Migrate one product surface', status: 'todo', priority: 'high' },
      { title: 'Roll out to the team', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Tokens defined', daysFromNow: 7 }, { title: 'Components shipped', daysFromNow: 25 }, { title: 'Team adopted', daysFromNow: 40 } ],
  },

  // ── Product Management ────────────────────────────────────
  {
    key: 'feature-launch', category: 'Product Management', Icon: Flag, name: 'Feature Launch', description: '7 tasks · 3 milestones',
    tasks: [
      { title: 'Write the feature spec', status: 'todo', priority: 'high' },
      { title: 'Align design and engineering', status: 'todo', priority: 'high' },
      { title: 'Build behind a feature flag', status: 'todo', priority: 'high' },
      { title: 'Internal dogfooding', status: 'todo', priority: 'medium' },
      { title: 'Beta with a subset of users', status: 'todo', priority: 'high' },
      { title: 'Gradual rollout to 100%', status: 'todo', priority: 'urgent' },
      { title: 'Measure adoption and impact', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Spec approved', daysFromNow: 5 }, { title: 'Beta live', daysFromNow: 20 }, { title: 'Full rollout', daysFromNow: 30 } ],
  },
  {
    key: 'user-research', category: 'Product Management', Icon: Users, name: 'User Research', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define research questions', status: 'todo', priority: 'high' },
      { title: 'Recruit participants', status: 'todo', priority: 'high' },
      { title: 'Write the interview script', status: 'todo', priority: 'medium' },
      { title: 'Run interviews / usability tests', status: 'todo', priority: 'high' },
      { title: 'Synthesize themes and insights', status: 'todo', priority: 'high' },
      { title: 'Share findings and recommendations', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Interviews done', daysFromNow: 14 }, { title: 'Insights shared', daysFromNow: 20 } ],
  },
  {
    key: 'backlog-grooming', category: 'Product Management', Icon: ClipboardList, name: 'Backlog Grooming', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Collect and tag all backlog items', status: 'todo', priority: 'medium' },
      { title: 'Merge duplicates, archive stale ones', status: 'todo', priority: 'medium' },
      { title: 'Score by impact vs effort', status: 'todo', priority: 'high' },
      { title: 'Write clear acceptance criteria', status: 'todo', priority: 'high' },
      { title: 'Prioritize next sprint', status: 'todo', priority: 'high' },
      { title: 'Review with the team', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Backlog cleaned', daysFromNow: 3 }, { title: 'Sprint planned', daysFromNow: 7 } ],
  },

  // ── Content & Media ───────────────────────────────────────
  {
    key: 'youtube-video', category: 'Content & Media', Icon: Video, name: 'YouTube Video', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Pick topic and hook', status: 'todo', priority: 'high' },
      { title: 'Write the script', status: 'todo', priority: 'high' },
      { title: 'Film the video', status: 'todo', priority: 'high' },
      { title: 'Edit and add b-roll', status: 'todo', priority: 'high' },
      { title: 'Design thumbnail', status: 'todo', priority: 'medium' },
      { title: 'Write title + description + tags', status: 'todo', priority: 'medium' },
      { title: 'Publish and promote', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Filmed', daysFromNow: 5 }, { title: 'Published', daysFromNow: 10 } ],
  },
  {
    key: 'podcast-episode', category: 'Content & Media', Icon: Mic, name: 'Podcast Episode', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Book the guest', status: 'todo', priority: 'high' },
      { title: 'Prep questions and outline', status: 'todo', priority: 'high' },
      { title: 'Record the episode', status: 'todo', priority: 'high' },
      { title: 'Edit audio and add intro/outro', status: 'todo', priority: 'medium' },
      { title: 'Write show notes', status: 'todo', priority: 'medium' },
      { title: 'Create audiograms / clips', status: 'todo', priority: 'low' },
      { title: 'Publish and share', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Recorded', daysFromNow: 5 }, { title: 'Episode live', daysFromNow: 9 } ],
  },
  {
    key: 'blog-post', category: 'Content & Media', Icon: Newspaper, name: 'Blog Article', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick topic and target keyword', status: 'todo', priority: 'high' },
      { title: 'Outline the article', status: 'todo', priority: 'high' },
      { title: 'Write the first draft', status: 'todo', priority: 'high' },
      { title: 'Edit and add visuals', status: 'todo', priority: 'medium' },
      { title: 'SEO pass (meta, links, alt text)', status: 'todo', priority: 'medium' },
      { title: 'Publish and distribute', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Draft done', daysFromNow: 4 }, { title: 'Published', daysFromNow: 7 } ],
  },

  // ── HR & Operations (more) ────────────────────────────────
  {
    key: 'performance-review', category: 'HR & Operations', Icon: Award, name: 'Performance Reviews', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Set the review cycle and timeline', status: 'todo', priority: 'high' },
      { title: 'Share self-assessment forms', status: 'todo', priority: 'medium' },
      { title: 'Collect peer / 360 feedback', status: 'todo', priority: 'high' },
      { title: 'Managers write reviews', status: 'todo', priority: 'high' },
      { title: 'Hold 1:1 review meetings', status: 'todo', priority: 'high' },
      { title: 'Finalize ratings and next-cycle goals', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Feedback collected', daysFromNow: 14 }, { title: 'Reviews delivered', daysFromNow: 28 } ],
  },
  {
    key: 'team-offsite', category: 'HR & Operations', Icon: Plane, name: 'Team Offsite', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Set offsite goals and budget', status: 'todo', priority: 'high' },
      { title: 'Pick dates and destination', status: 'todo', priority: 'high' },
      { title: 'Book travel and lodging', status: 'todo', priority: 'high' },
      { title: 'Plan agenda and activities', status: 'todo', priority: 'medium' },
      { title: 'Arrange meals and logistics', status: 'todo', priority: 'medium' },
      { title: 'Run the offsite', status: 'todo', priority: 'urgent' },
      { title: 'Collect feedback and follow-ups', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Booked', daysFromNow: 14 }, { title: 'Offsite done', daysFromNow: 45 } ],
  },
  {
    key: 'policy-rollout', category: 'HR & Operations', Icon: Shield, name: 'Policy Rollout', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Draft the new policy', status: 'todo', priority: 'high' },
      { title: 'Legal / compliance review', status: 'todo', priority: 'high' },
      { title: 'Get leadership sign-off', status: 'todo', priority: 'high' },
      { title: 'Communicate to the team', status: 'todo', priority: 'high' },
      { title: 'Update handbook and docs', status: 'todo', priority: 'medium' },
      { title: 'Answer questions and enforce', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Approved', daysFromNow: 10 }, { title: 'Rolled out', daysFromNow: 20 } ],
  },

  // ── Finance ───────────────────────────────────────────────
  {
    key: 'monthly-close', category: 'Finance', Icon: Receipt, name: 'Monthly Books Close', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Import and categorize transactions', status: 'todo', priority: 'high' },
      { title: 'Reconcile bank and card accounts', status: 'todo', priority: 'high' },
      { title: 'Chase and record outstanding invoices', status: 'todo', priority: 'medium' },
      { title: 'Record expenses and receipts', status: 'todo', priority: 'medium' },
      { title: 'Review P&L and balance sheet', status: 'todo', priority: 'high' },
      { title: 'Flag anomalies', status: 'todo', priority: 'medium' },
      { title: 'Send monthly summary', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Reconciled', daysFromNow: 3 }, { title: 'Books closed', daysFromNow: 5 } ],
  },
  {
    key: 'fundraising', category: 'Finance', Icon: TrendingUp, name: 'Fundraising Round', description: '8 tasks · 3 milestones',
    tasks: [
      { title: 'Define raise amount and use of funds', status: 'todo', priority: 'high' },
      { title: 'Build pitch deck', status: 'todo', priority: 'high' },
      { title: 'Prepare financial model', status: 'todo', priority: 'high' },
      { title: 'Build target investor list', status: 'todo', priority: 'medium' },
      { title: 'Warm intros and outreach', status: 'todo', priority: 'high' },
      { title: 'Run investor meetings', status: 'todo', priority: 'urgent' },
      { title: 'Due diligence and term sheet', status: 'todo', priority: 'high' },
      { title: 'Close the round', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Deck ready', daysFromNow: 10 }, { title: 'Meetings underway', daysFromNow: 30 }, { title: 'Round closed', daysFromNow: 75 } ],
  },
  {
    key: 'budget-planning', category: 'Finance', Icon: BarChart, name: 'Annual Budget', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Review last year’s actuals', status: 'todo', priority: 'high' },
      { title: 'Gather department requests', status: 'todo', priority: 'high' },
      { title: 'Forecast revenue', status: 'todo', priority: 'high' },
      { title: 'Allocate budgets by team', status: 'todo', priority: 'high' },
      { title: 'Build scenarios (base / lean / growth)', status: 'todo', priority: 'medium' },
      { title: 'Present and approve', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Draft budget', daysFromNow: 10 }, { title: 'Budget approved', daysFromNow: 21 } ],
  },

  // ── Customer Support ──────────────────────────────────────
  {
    key: 'support-sprint', category: 'Customer Support', Icon: LifeBuoy, name: 'Support Backlog Sprint', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Triage and tag open tickets', status: 'todo', priority: 'high' },
      { title: 'Resolve quick wins first', status: 'todo', priority: 'high' },
      { title: 'Escalate bugs to engineering', status: 'todo', priority: 'high' },
      { title: 'Reply to aging tickets', status: 'todo', priority: 'urgent' },
      { title: 'Identify top recurring issues', status: 'todo', priority: 'medium' },
      { title: 'Write macros for common replies', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Backlog triaged', daysFromNow: 2 }, { title: 'Inbox at zero', daysFromNow: 7 } ],
  },
  {
    key: 'help-docs', category: 'Customer Support', Icon: HelpCircle, name: 'Help Center / Docs', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List top questions from support', status: 'todo', priority: 'high' },
      { title: 'Outline article structure', status: 'todo', priority: 'medium' },
      { title: 'Write getting-started guides', status: 'todo', priority: 'high' },
      { title: 'Add screenshots and videos', status: 'todo', priority: 'medium' },
      { title: 'Publish to help center', status: 'todo', priority: 'medium' },
      { title: 'Link docs inside the product', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Core articles live', daysFromNow: 10 }, { title: 'Help center launched', daysFromNow: 18 } ],
  },
  {
    key: 'customer-feedback', category: 'Customer Support', Icon: MessageSquare, name: 'Customer Feedback Loop', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Set up a feedback channel', status: 'todo', priority: 'high' },
      { title: 'Send an NPS / CSAT survey', status: 'todo', priority: 'high' },
      { title: 'Interview a few power users', status: 'todo', priority: 'medium' },
      { title: 'Tag and theme the feedback', status: 'todo', priority: 'high' },
      { title: 'Share top requests with product', status: 'todo', priority: 'medium' },
      { title: 'Close the loop with customers', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Survey sent', daysFromNow: 5 }, { title: 'Insights shared', daysFromNow: 14 } ],
  },

  // ── Education ─────────────────────────────────────────────
  {
    key: 'course-cohort', category: 'Education', Icon: GraduationCap, name: 'Cohort Course', description: '7 tasks · 3 milestones',
    tasks: [
      { title: 'Design curriculum and schedule', status: 'todo', priority: 'high' },
      { title: 'Open enrollment', status: 'todo', priority: 'high' },
      { title: 'Prepare week 1 materials', status: 'todo', priority: 'high' },
      { title: 'Run live sessions', status: 'todo', priority: 'high' },
      { title: 'Grade assignments / give feedback', status: 'todo', priority: 'medium' },
      { title: 'Host office hours', status: 'todo', priority: 'medium' },
      { title: 'Graduation and certificates', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Enrollment closed', daysFromNow: 14 }, { title: 'Cohort starts', daysFromNow: 21 }, { title: 'Cohort ends', daysFromNow: 60 } ],
  },
  {
    key: 'workshop-prep', category: 'Education', Icon: Presentation, name: 'Workshop Prep', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define learning outcomes', status: 'todo', priority: 'high' },
      { title: 'Build slides and exercises', status: 'todo', priority: 'high' },
      { title: 'Prepare handouts / worksheets', status: 'todo', priority: 'medium' },
      { title: 'Do a dry run', status: 'todo', priority: 'medium' },
      { title: 'Set up room / virtual room', status: 'todo', priority: 'medium' },
      { title: 'Run the workshop', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Materials ready', daysFromNow: 7 }, { title: 'Workshop delivered', daysFromNow: 14 } ],
  },
  {
    key: 'study-plan', category: 'Education', Icon: CheckSquare, name: 'Exam Study Plan', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'List all topics to cover', status: 'todo', priority: 'high' },
      { title: 'Break topics into a weekly schedule', status: 'todo', priority: 'high' },
      { title: 'Gather notes and resources', status: 'todo', priority: 'medium' },
      { title: 'Do daily study blocks', status: 'todo', priority: 'high' },
      { title: 'Take practice tests', status: 'todo', priority: 'high' },
      { title: 'Review weak areas', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Half syllabus done', daysFromNow: 14 }, { title: 'Full syllabus done', daysFromNow: 28 }, { title: 'Exam day', daysFromNow: 35 } ],
  },

  // ── Personal & Productivity (more) ────────────────────────
  {
    key: 'home-reno', category: 'Personal & Productivity', Icon: Home, name: 'Home Renovation', description: '7 tasks · 3 milestones',
    tasks: [
      { title: 'Set budget and scope', status: 'todo', priority: 'high' },
      { title: 'Get contractor quotes', status: 'todo', priority: 'high' },
      { title: 'Finalize design and materials', status: 'todo', priority: 'medium' },
      { title: 'Order materials', status: 'todo', priority: 'medium' },
      { title: 'Demolition and prep', status: 'todo', priority: 'high' },
      { title: 'Main build / installation', status: 'todo', priority: 'high' },
      { title: 'Final walkthrough and snag list', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Contractor booked', daysFromNow: 10 }, { title: 'Build starts', daysFromNow: 21 }, { title: 'Project done', daysFromNow: 60 } ],
  },
  {
    key: 'trip-planning', category: 'Personal & Productivity', Icon: Compass, name: 'Trip Planning', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Pick destination and dates', status: 'todo', priority: 'high' },
      { title: 'Set a budget', status: 'todo', priority: 'medium' },
      { title: 'Book flights', status: 'todo', priority: 'high' },
      { title: 'Book accommodation', status: 'todo', priority: 'high' },
      { title: 'Plan daily itinerary', status: 'todo', priority: 'medium' },
      { title: 'Sort visas / documents / insurance', status: 'todo', priority: 'high' },
      { title: 'Pack and prep', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Flights + stay booked', daysFromNow: 14 }, { title: 'Departure', daysFromNow: 45 } ],
  },
  {
    key: 'fitness-plan', category: 'Personal & Productivity', Icon: Dumbbell, name: 'Fitness Plan', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Set a specific fitness goal', status: 'todo', priority: 'high' },
      { title: 'Design a weekly workout split', status: 'todo', priority: 'high' },
      { title: 'Plan meals and nutrition', status: 'todo', priority: 'medium' },
      { title: 'Track workouts daily', status: 'todo', priority: 'high' },
      { title: 'Log progress weekly', status: 'todo', priority: 'medium' },
      { title: 'Adjust plan monthly', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Plan set', daysFromNow: 2 }, { title: 'Week 4 check-in', daysFromNow: 28 }, { title: 'Goal reached', daysFromNow: 84 } ],
  },

  // -- +60 templates -----------------------------------------
  {
    key: 'lead-magnet', category: 'Business & Sales', Icon: Gift, name: 'Lead Magnet Funnel', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick a high-value topic for the offer', status: 'todo', priority: 'high' },
      { title: 'Create the lead magnet asset', status: 'todo', priority: 'high' },
      { title: 'Build the landing page and form', status: 'todo', priority: 'high' },
      { title: 'Set up the email delivery', status: 'todo', priority: 'medium' },
      { title: 'Drive traffic to the page', status: 'todo', priority: 'medium' },
      { title: 'Track opt-in conversion', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Asset ready', daysFromNow: 7 }, { title: 'Funnel live', daysFromNow: 14 } ],
  },
  {
    key: 'proposal-pipeline', category: 'Business & Sales', Icon: FileText, name: 'Proposal & Quote Pipeline', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Build a reusable proposal template', status: 'todo', priority: 'high' },
      { title: 'Collect requirements from the lead', status: 'todo', priority: 'high' },
      { title: 'Draft scope and pricing', status: 'todo', priority: 'high' },
      { title: 'Internal review and approval', status: 'todo', priority: 'medium' },
      { title: 'Send proposal', status: 'todo', priority: 'urgent' },
      { title: 'Follow up and close', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Template ready', daysFromNow: 3 }, { title: 'Proposal sent', daysFromNow: 10 }, { title: 'Deal closed', daysFromNow: 25 } ],
  },
  {
    key: 'crm-cleanup', category: 'Business & Sales', Icon: Database, name: 'CRM Cleanup', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Export and audit current records', status: 'todo', priority: 'high' },
      { title: 'Merge duplicate contacts', status: 'todo', priority: 'high' },
      { title: 'Fix missing or stale fields', status: 'todo', priority: 'medium' },
      { title: 'Standardize stages and tags', status: 'todo', priority: 'medium' },
      { title: 'Archive dead leads', status: 'todo', priority: 'low' },
      { title: 'Document CRM hygiene rules', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Audit done', daysFromNow: 3 }, { title: 'CRM clean', daysFromNow: 10 } ],
  },
  {
    key: 'upsell-campaign', category: 'Business & Sales', Icon: TrendingUp, name: 'Upsell / Renewal Push', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Identify accounts up for renewal', status: 'todo', priority: 'high' },
      { title: 'Segment by upsell potential', status: 'todo', priority: 'high' },
      { title: 'Craft tailored offers', status: 'todo', priority: 'medium' },
      { title: 'Reach out to each account', status: 'todo', priority: 'high' },
      { title: 'Handle objections', status: 'todo', priority: 'medium' },
      { title: 'Log renewals and expansions', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'List segmented', daysFromNow: 5 }, { title: 'Outreach done', daysFromNow: 20 } ],
  },
  {
    key: 'trade-show', category: 'Business & Sales', Icon: Store, name: 'Trade Show / Expo', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Book booth and logistics', status: 'todo', priority: 'high' },
      { title: 'Design booth and collateral', status: 'todo', priority: 'high' },
      { title: 'Set lead-capture process', status: 'todo', priority: 'medium' },
      { title: 'Promote attendance beforehand', status: 'todo', priority: 'medium' },
      { title: 'Staff and run the booth', status: 'todo', priority: 'urgent' },
      { title: 'Follow up with captured leads', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Booth booked', daysFromNow: 20 }, { title: 'Show day', daysFromNow: 45 }, { title: 'Leads followed up', daysFromNow: 52 } ],
  },
  {
    key: 'email-newsletter', category: 'Marketing', Icon: Mail, name: 'Email Newsletter', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define audience and cadence', status: 'todo', priority: 'high' },
      { title: 'Outline this issue', status: 'todo', priority: 'high' },
      { title: 'Write the copy', status: 'todo', priority: 'high' },
      { title: 'Design the template', status: 'todo', priority: 'medium' },
      { title: 'Set up and test send', status: 'todo', priority: 'medium' },
      { title: 'Send and review metrics', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Draft ready', daysFromNow: 3 }, { title: 'Sent', daysFromNow: 5 } ],
  },
  {
    key: 'social-media-month', category: 'Marketing', Icon: Share2, name: 'Social Media Month', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Set goals and target channels', status: 'todo', priority: 'high' },
      { title: 'Plan the content pillars', status: 'todo', priority: 'high' },
      { title: 'Draft 20 posts', status: 'todo', priority: 'high' },
      { title: 'Create graphics', status: 'todo', priority: 'medium' },
      { title: 'Schedule the month', status: 'todo', priority: 'medium' },
      { title: 'Review engagement weekly', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Calendar filled', daysFromNow: 5 }, { title: 'Month scheduled', daysFromNow: 10 } ],
  },
  {
    key: 'brand-refresh', category: 'Marketing', Icon: Palette, name: 'Brand Refresh', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Audit the current brand', status: 'todo', priority: 'high' },
      { title: 'Define new positioning', status: 'todo', priority: 'high' },
      { title: 'Design logo and palette', status: 'todo', priority: 'high' },
      { title: 'Build brand guidelines', status: 'todo', priority: 'medium' },
      { title: 'Update key assets', status: 'todo', priority: 'medium' },
      { title: 'Roll out across channels', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Direction set', daysFromNow: 10 }, { title: 'Assets updated', daysFromNow: 30 } ],
  },
  {
    key: 'webinar', category: 'Marketing', Icon: Video, name: 'Webinar', description: '7 tasks · 2 milestones',
    tasks: [
      { title: 'Pick topic and speaker', status: 'todo', priority: 'high' },
      { title: 'Set date and platform', status: 'todo', priority: 'high' },
      { title: 'Build registration page', status: 'todo', priority: 'medium' },
      { title: 'Promote the webinar', status: 'todo', priority: 'high' },
      { title: 'Prepare slides and run-of-show', status: 'todo', priority: 'medium' },
      { title: 'Host and record', status: 'todo', priority: 'urgent' },
      { title: 'Send replay and follow-up', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Registration open', daysFromNow: 7 }, { title: 'Webinar day', daysFromNow: 21 } ],
  },
  {
    key: 'influencer-campaign', category: 'Marketing', Icon: Star, name: 'Influencer Campaign', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define goals and budget', status: 'todo', priority: 'high' },
      { title: 'Shortlist relevant creators', status: 'todo', priority: 'high' },
      { title: 'Reach out and negotiate', status: 'todo', priority: 'high' },
      { title: 'Brief creators on the message', status: 'todo', priority: 'medium' },
      { title: 'Review and approve content', status: 'todo', priority: 'medium' },
      { title: 'Track results and ROI', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Creators booked', daysFromNow: 10 }, { title: 'Campaign live', daysFromNow: 20 } ],
  },
  {
    key: 'design-handoff', category: 'Design & Engineering', Icon: PenTool, name: 'Design Handoff', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Finalize the designs', status: 'todo', priority: 'high' },
      { title: 'Annotate specs and states', status: 'todo', priority: 'high' },
      { title: 'Export assets', status: 'todo', priority: 'medium' },
      { title: 'Document interactions', status: 'todo', priority: 'medium' },
      { title: 'Walk engineering through it', status: 'todo', priority: 'high' },
      { title: 'Answer follow-up questions', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Specs ready', daysFromNow: 3 }, { title: 'Handoff done', daysFromNow: 5 } ],
  },
  {
    key: 'accessibility-audit', category: 'Design & Engineering', Icon: Search, name: 'Accessibility Audit', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Run automated a11y scans', status: 'todo', priority: 'high' },
      { title: 'Manual keyboard and screen-reader test', status: 'todo', priority: 'high' },
      { title: 'Check color contrast', status: 'todo', priority: 'medium' },
      { title: 'Log issues by severity', status: 'todo', priority: 'high' },
      { title: 'Fix critical issues', status: 'todo', priority: 'urgent' },
      { title: 'Re-test and document', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Issues logged', daysFromNow: 5 }, { title: 'Critical fixed', daysFromNow: 18 } ],
  },
  {
    key: 'tech-debt-sprint', category: 'Design & Engineering', Icon: Wrench, name: 'Tech Debt Sprint', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Inventory known tech debt', status: 'todo', priority: 'high' },
      { title: 'Prioritize by risk and effort', status: 'todo', priority: 'high' },
      { title: 'Refactor the worst offenders', status: 'todo', priority: 'high' },
      { title: 'Add missing tests', status: 'todo', priority: 'medium' },
      { title: 'Update docs', status: 'todo', priority: 'low' },
      { title: 'Review and merge', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Debt prioritized', daysFromNow: 2 }, { title: 'Sprint done', daysFromNow: 14 } ],
  },
  {
    key: 'infra-migration', category: 'Design & Engineering', Icon: Server, name: 'Infra Migration', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Document current architecture', status: 'todo', priority: 'high' },
      { title: 'Plan the target setup', status: 'todo', priority: 'high' },
      { title: 'Set up the new environment', status: 'todo', priority: 'high' },
      { title: 'Migrate data with a dry run', status: 'todo', priority: 'high' },
      { title: 'Cut over with rollback ready', status: 'todo', priority: 'urgent' },
      { title: 'Monitor and decommission old', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Plan approved', daysFromNow: 7 }, { title: 'Dry run done', daysFromNow: 20 }, { title: 'Cutover complete', daysFromNow: 30 } ],
  },
  {
    key: 'security-review', category: 'Design & Engineering', Icon: Shield, name: 'Security Review', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Map the attack surface', status: 'todo', priority: 'high' },
      { title: 'Review auth and access control', status: 'todo', priority: 'high' },
      { title: 'Scan dependencies for CVEs', status: 'todo', priority: 'medium' },
      { title: 'Pen-test critical flows', status: 'todo', priority: 'high' },
      { title: 'Fix high-severity findings', status: 'todo', priority: 'urgent' },
      { title: 'Document and schedule re-review', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Findings logged', daysFromNow: 7 }, { title: 'High fixed', daysFromNow: 21 } ],
  },
  {
    key: 'competitor-analysis', category: 'Product Management', Icon: Search, name: 'Competitor Analysis', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List key competitors', status: 'todo', priority: 'high' },
      { title: 'Compare features and pricing', status: 'todo', priority: 'high' },
      { title: 'Analyze positioning and messaging', status: 'todo', priority: 'medium' },
      { title: 'Read their reviews for gaps', status: 'todo', priority: 'medium' },
      { title: 'Summarize threats and openings', status: 'todo', priority: 'high' },
      { title: 'Share recommendations', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Research done', daysFromNow: 7 }, { title: 'Report shared', daysFromNow: 12 } ],
  },
  {
    key: 'beta-program', category: 'Product Management', Icon: Users, name: 'Beta Program', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Define beta goals and scope', status: 'todo', priority: 'high' },
      { title: 'Recruit and vet testers', status: 'todo', priority: 'high' },
      { title: 'Set up feedback channels', status: 'todo', priority: 'medium' },
      { title: 'Ship the beta build', status: 'todo', priority: 'high' },
      { title: 'Collect and triage feedback', status: 'todo', priority: 'high' },
      { title: 'Decide go/no-go for GA', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Testers onboarded', daysFromNow: 7 }, { title: 'Beta running', daysFromNow: 14 }, { title: 'GA decision', daysFromNow: 35 } ],
  },
  {
    key: 'pricing-experiment', category: 'Product Management', Icon: DollarSign, name: 'Pricing Experiment', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Review current pricing data', status: 'todo', priority: 'high' },
      { title: 'Form a hypothesis', status: 'todo', priority: 'high' },
      { title: 'Design the test and segments', status: 'todo', priority: 'medium' },
      { title: 'Ship the price change', status: 'todo', priority: 'high' },
      { title: 'Measure conversion and revenue', status: 'todo', priority: 'high' },
      { title: 'Decide to keep or revert', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Test live', daysFromNow: 7 }, { title: 'Results in', daysFromNow: 30 } ],
  },
  {
    key: 'okr-planning', category: 'Product Management', Icon: Target, name: 'OKR Planning', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Review last cycle outcomes', status: 'todo', priority: 'high' },
      { title: 'Draft objectives', status: 'todo', priority: 'high' },
      { title: 'Define measurable key results', status: 'todo', priority: 'high' },
      { title: 'Align with each team', status: 'todo', priority: 'medium' },
      { title: 'Finalize and publish OKRs', status: 'todo', priority: 'high' },
      { title: 'Set weekly check-in cadence', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Draft ready', daysFromNow: 5 }, { title: 'OKRs published', daysFromNow: 12 } ],
  },
  {
    key: 'release-notes', category: 'Product Management', Icon: FileText, name: 'Release Notes & Changelog', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Collect merged changes', status: 'todo', priority: 'medium' },
      { title: 'Group by feature and fix', status: 'todo', priority: 'medium' },
      { title: 'Write user-facing notes', status: 'todo', priority: 'high' },
      { title: 'Add screenshots or GIFs', status: 'todo', priority: 'low' },
      { title: 'Review with the team', status: 'todo', priority: 'medium' },
      { title: 'Publish and announce', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Draft ready', daysFromNow: 2 }, { title: 'Published', daysFromNow: 4 } ],
  },
  {
    key: 'ebook', category: 'Content & Media', Icon: BookOpen, name: 'Ebook / Guide', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick topic and outline chapters', status: 'todo', priority: 'high' },
      { title: 'Write the draft', status: 'todo', priority: 'high' },
      { title: 'Edit and proofread', status: 'todo', priority: 'medium' },
      { title: 'Design the layout', status: 'todo', priority: 'medium' },
      { title: 'Build the download page', status: 'todo', priority: 'medium' },
      { title: 'Launch and promote', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Draft done', daysFromNow: 14 }, { title: 'Ebook live', daysFromNow: 25 } ],
  },
  {
    key: 'photo-shoot', category: 'Content & Media', Icon: Camera, name: 'Photo / Video Shoot', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Define the shot list', status: 'todo', priority: 'high' },
      { title: 'Book location and talent', status: 'todo', priority: 'high' },
      { title: 'Arrange gear and crew', status: 'todo', priority: 'medium' },
      { title: 'Run the shoot', status: 'todo', priority: 'urgent' },
      { title: 'Cull and edit selects', status: 'todo', priority: 'high' },
      { title: 'Deliver final assets', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Pre-pro done', daysFromNow: 7 }, { title: 'Shoot day', daysFromNow: 14 }, { title: 'Delivered', daysFromNow: 21 } ],
  },
  {
    key: 'case-study-content', category: 'Content & Media', Icon: FileText, name: 'Case Study Write-up', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick a strong customer story', status: 'todo', priority: 'high' },
      { title: 'Interview the customer', status: 'todo', priority: 'high' },
      { title: 'Draft the narrative', status: 'todo', priority: 'high' },
      { title: 'Get customer approval', status: 'todo', priority: 'medium' },
      { title: 'Design and format', status: 'todo', priority: 'medium' },
      { title: 'Publish and share', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Interview done', daysFromNow: 5 }, { title: 'Published', daysFromNow: 15 } ],
  },
  {
    key: 'content-repurpose', category: 'Content & Media', Icon: Repeat, name: 'Content Repurposing', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick a top-performing piece', status: 'todo', priority: 'high' },
      { title: 'Break it into social snippets', status: 'todo', priority: 'medium' },
      { title: 'Turn it into a video or reel', status: 'todo', priority: 'medium' },
      { title: 'Write an email version', status: 'todo', priority: 'low' },
      { title: 'Schedule across channels', status: 'todo', priority: 'medium' },
      { title: 'Track which format wins', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Snippets ready', daysFromNow: 5 }, { title: 'All published', daysFromNow: 12 } ],
  },
  {
    key: 'webinar-content', category: 'Content & Media', Icon: Presentation, name: 'Webinar Content Prep', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define learning outcomes', status: 'todo', priority: 'high' },
      { title: 'Outline the talk', status: 'todo', priority: 'high' },
      { title: 'Build the slides', status: 'todo', priority: 'high' },
      { title: 'Prepare a demo or examples', status: 'todo', priority: 'medium' },
      { title: 'Rehearse and time it', status: 'todo', priority: 'medium' },
      { title: 'Prep Q&A and handouts', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Slides ready', daysFromNow: 7 }, { title: 'Rehearsed', daysFromNow: 10 } ],
  },
  {
    key: 'offboarding', category: 'HR & Operations', Icon: UserCheck, name: 'Employee Offboarding', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Confirm last working day', status: 'todo', priority: 'high' },
      { title: 'Revoke accounts and access', status: 'todo', priority: 'high' },
      { title: 'Recover equipment', status: 'todo', priority: 'high' },
      { title: 'Run a knowledge transfer', status: 'todo', priority: 'medium' },
      { title: 'Hold an exit interview', status: 'todo', priority: 'medium' },
      { title: 'Process final pay and benefits', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Access revoked', daysFromNow: 2 }, { title: 'Offboarding complete', daysFromNow: 7 } ],
  },
  {
    key: 'payroll-run', category: 'HR & Operations', Icon: Wallet, name: 'Payroll Run', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Collect timesheets and changes', status: 'todo', priority: 'high' },
      { title: 'Verify hours and adjustments', status: 'todo', priority: 'high' },
      { title: 'Calculate pay and deductions', status: 'todo', priority: 'high' },
      { title: 'Review before submitting', status: 'todo', priority: 'medium' },
      { title: 'Process the payroll', status: 'todo', priority: 'urgent' },
      { title: 'Send payslips', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Verified', daysFromNow: 2 }, { title: 'Payroll sent', daysFromNow: 4 } ],
  },
  {
    key: 'vendor-onboarding', category: 'HR & Operations', Icon: Briefcase, name: 'Vendor Onboarding', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Collect vendor documents', status: 'todo', priority: 'high' },
      { title: 'Run due diligence', status: 'todo', priority: 'high' },
      { title: 'Negotiate and sign contract', status: 'todo', priority: 'high' },
      { title: 'Set up in the finance system', status: 'todo', priority: 'medium' },
      { title: 'Grant necessary access', status: 'todo', priority: 'medium' },
      { title: 'Schedule a kickoff', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Contract signed', daysFromNow: 7 }, { title: 'Vendor active', daysFromNow: 14 } ],
  },
  {
    key: 'office-move', category: 'HR & Operations', Icon: Building2, name: 'Office Move', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Set budget and timeline', status: 'todo', priority: 'high' },
      { title: 'Find and secure the new space', status: 'todo', priority: 'high' },
      { title: 'Plan the layout', status: 'todo', priority: 'medium' },
      { title: 'Book movers and IT setup', status: 'todo', priority: 'high' },
      { title: 'Notify staff and update addresses', status: 'todo', priority: 'medium' },
      { title: 'Move and settle in', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Space secured', daysFromNow: 14 }, { title: 'Move day', daysFromNow: 45 } ],
  },
  {
    key: 'compliance-audit', category: 'HR & Operations', Icon: Scale, name: 'Compliance Audit', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Identify applicable regulations', status: 'todo', priority: 'high' },
      { title: 'Gather policies and evidence', status: 'todo', priority: 'high' },
      { title: 'Find gaps against requirements', status: 'todo', priority: 'high' },
      { title: 'Remediate the gaps', status: 'todo', priority: 'urgent' },
      { title: 'Document controls', status: 'todo', priority: 'medium' },
      { title: 'Prepare for external audit', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Gaps found', daysFromNow: 10 }, { title: 'Remediated', daysFromNow: 30 } ],
  },
  {
    key: 'sprint-planning', category: 'Team Management', Icon: ListChecks, name: 'Sprint Planning', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Groom and estimate the backlog', status: 'todo', priority: 'high' },
      { title: 'Set the sprint goal', status: 'todo', priority: 'high' },
      { title: 'Pull in capacity-fit work', status: 'todo', priority: 'high' },
      { title: 'Assign owners', status: 'todo', priority: 'medium' },
      { title: 'Confirm acceptance criteria', status: 'todo', priority: 'medium' },
      { title: 'Kick off the sprint', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Backlog ready', daysFromNow: 1 }, { title: 'Sprint started', daysFromNow: 2 } ],
  },
  {
    key: 'team-1on1s', category: 'Team Management', Icon: MessageSquare, name: '1:1s & Check-ins', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Schedule recurring 1:1s', status: 'todo', priority: 'high' },
      { title: 'Prepare talking points', status: 'todo', priority: 'medium' },
      { title: 'Discuss goals and blockers', status: 'todo', priority: 'high' },
      { title: 'Capture action items', status: 'todo', priority: 'medium' },
      { title: 'Follow up on last actions', status: 'todo', priority: 'medium' },
      { title: 'Log feedback and growth notes', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Cadence set', daysFromNow: 2 }, { title: 'First round done', daysFromNow: 7 } ],
  },
  {
    key: 'meeting-agenda', category: 'Team Management', Icon: Calendar, name: 'Weekly Team Meeting', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Collect agenda items', status: 'todo', priority: 'medium' },
      { title: 'Prioritize the topics', status: 'todo', priority: 'medium' },
      { title: 'Share the agenda ahead', status: 'todo', priority: 'high' },
      { title: 'Run the meeting on time', status: 'todo', priority: 'high' },
      { title: 'Capture decisions and owners', status: 'todo', priority: 'high' },
      { title: 'Send notes and follow-ups', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Agenda sent', daysFromNow: 1 }, { title: 'Notes shared', daysFromNow: 2 } ],
  },
  {
    key: 'team-goals', category: 'Team Management', Icon: Flag, name: 'Team Goals (Quarter)', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Review last quarter results', status: 'todo', priority: 'high' },
      { title: 'Draft this quarter goals', status: 'todo', priority: 'high' },
      { title: 'Break goals into workstreams', status: 'todo', priority: 'high' },
      { title: 'Assign owners', status: 'todo', priority: 'medium' },
      { title: 'Set check-in rhythm', status: 'todo', priority: 'medium' },
      { title: 'Publish to the team', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Goals drafted', daysFromNow: 5 }, { title: 'Published', daysFromNow: 10 } ],
  },
  {
    key: 'remote-onboarding', category: 'Remote Teams', Icon: UserPlus, name: 'Remote Onboarding', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Ship equipment ahead of day one', status: 'todo', priority: 'high' },
      { title: 'Set up accounts and access', status: 'todo', priority: 'high' },
      { title: 'Send a welcome and schedule', status: 'todo', priority: 'medium' },
      { title: 'Assign an onboarding buddy', status: 'todo', priority: 'medium' },
      { title: 'Book intro calls across the team', status: 'todo', priority: 'medium' },
      { title: 'Set 30/60/90 goals', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Day 1 ready', daysFromNow: 5 }, { title: 'First week done', daysFromNow: 12 } ],
  },
  {
    key: 'async-standup', category: 'Remote Teams', Icon: Clock, name: 'Async Standup Setup', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick a tool or channel', status: 'todo', priority: 'high' },
      { title: 'Define the standup format', status: 'todo', priority: 'high' },
      { title: 'Set the daily prompt time', status: 'todo', priority: 'medium' },
      { title: 'Onboard the team to it', status: 'todo', priority: 'medium' },
      { title: 'Run it for a week', status: 'todo', priority: 'high' },
      { title: 'Refine based on feedback', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Format set', daysFromNow: 3 }, { title: 'Running smoothly', daysFromNow: 14 } ],
  },
  {
    key: 'virtual-teambuilding', category: 'Remote Teams', Icon: Users, name: 'Virtual Team Building', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick an activity and date', status: 'todo', priority: 'high' },
      { title: 'Send invites and set expectations', status: 'todo', priority: 'medium' },
      { title: 'Prepare materials or prompts', status: 'todo', priority: 'medium' },
      { title: 'Host the session', status: 'todo', priority: 'urgent' },
      { title: 'Gather feedback', status: 'todo', priority: 'low' },
      { title: 'Plan the next one', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Scheduled', daysFromNow: 7 }, { title: 'Event done', daysFromNow: 14 } ],
  },
  {
    key: 'distributed-handbook', category: 'Remote Teams', Icon: BookOpen, name: 'Remote Handbook', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List the topics to cover', status: 'todo', priority: 'high' },
      { title: 'Document tools and norms', status: 'todo', priority: 'high' },
      { title: 'Write communication guidelines', status: 'todo', priority: 'medium' },
      { title: 'Add time-zone and meeting rules', status: 'todo', priority: 'medium' },
      { title: 'Review with the team', status: 'todo', priority: 'medium' },
      { title: 'Publish and link everywhere', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Draft ready', daysFromNow: 10 }, { title: 'Handbook live', daysFromNow: 18 } ],
  },
  {
    key: 'expense-audit', category: 'Finance', Icon: Receipt, name: 'Expense Audit', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pull the expense report', status: 'todo', priority: 'high' },
      { title: 'Categorize all spend', status: 'todo', priority: 'high' },
      { title: 'Flag anomalies and duplicates', status: 'todo', priority: 'high' },
      { title: 'Chase missing receipts', status: 'todo', priority: 'medium' },
      { title: 'Identify savings', status: 'todo', priority: 'medium' },
      { title: 'Share findings', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Categorized', daysFromNow: 3 }, { title: 'Findings shared', daysFromNow: 7 } ],
  },
  {
    key: 'invoice-chase', category: 'Finance', Icon: FileText, name: 'Invoice Collections', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List overdue invoices', status: 'todo', priority: 'high' },
      { title: 'Sort by age and amount', status: 'todo', priority: 'high' },
      { title: 'Send friendly reminders', status: 'todo', priority: 'high' },
      { title: 'Escalate the worst offenders', status: 'todo', priority: 'urgent' },
      { title: 'Offer payment options', status: 'todo', priority: 'medium' },
      { title: 'Record payments received', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Reminders sent', daysFromNow: 2 }, { title: 'Overdue cleared', daysFromNow: 20 } ],
  },
  {
    key: 'tax-filing', category: 'Finance', Icon: Scale, name: 'Tax Filing', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Gather income and expense records', status: 'todo', priority: 'high' },
      { title: 'Reconcile the accounts', status: 'todo', priority: 'high' },
      { title: 'Compute liabilities', status: 'todo', priority: 'high' },
      { title: 'Review with an accountant', status: 'todo', priority: 'medium' },
      { title: 'File the returns', status: 'todo', priority: 'urgent' },
      { title: 'Archive the documents', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Records ready', daysFromNow: 10 }, { title: 'Filed', daysFromNow: 25 } ],
  },
  {
    key: 'pricing-model', category: 'Finance', Icon: PieChart, name: 'Pricing Model Build', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Gather cost and margin data', status: 'todo', priority: 'high' },
      { title: 'Research market benchmarks', status: 'todo', priority: 'high' },
      { title: 'Build the pricing model', status: 'todo', priority: 'high' },
      { title: 'Run scenarios', status: 'todo', priority: 'medium' },
      { title: 'Pressure-test with the team', status: 'todo', priority: 'medium' },
      { title: 'Finalize and document', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Model built', daysFromNow: 7 }, { title: 'Approved', daysFromNow: 14 } ],
  },
  {
    key: 'csat-improvement', category: 'Customer Support', Icon: Heart, name: 'CSAT Improvement', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pull recent CSAT scores', status: 'todo', priority: 'high' },
      { title: 'Read low-score comments', status: 'todo', priority: 'high' },
      { title: 'Find the top pain themes', status: 'todo', priority: 'high' },
      { title: 'Fix the quickest wins', status: 'todo', priority: 'urgent' },
      { title: 'Update macros and training', status: 'todo', priority: 'medium' },
      { title: 'Re-measure CSAT', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Themes found', daysFromNow: 5 }, { title: 'CSAT re-measured', daysFromNow: 30 } ],
  },
  {
    key: 'knowledge-base', category: 'Customer Support', Icon: BookOpen, name: 'Knowledge Base Build', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List the top asked questions', status: 'todo', priority: 'high' },
      { title: 'Structure categories', status: 'todo', priority: 'medium' },
      { title: 'Write core articles', status: 'todo', priority: 'high' },
      { title: 'Add visuals', status: 'todo', priority: 'medium' },
      { title: 'Publish the help center', status: 'todo', priority: 'medium' },
      { title: 'Link articles in-product', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Articles live', daysFromNow: 10 }, { title: 'Launched', daysFromNow: 18 } ],
  },
  {
    key: 'churn-winback', category: 'Customer Support', Icon: Repeat, name: 'Churn Win-back', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pull recently churned users', status: 'todo', priority: 'high' },
      { title: 'Segment by churn reason', status: 'todo', priority: 'high' },
      { title: 'Craft win-back offers', status: 'todo', priority: 'medium' },
      { title: 'Reach out personally', status: 'todo', priority: 'high' },
      { title: 'Track re-activations', status: 'todo', priority: 'medium' },
      { title: 'Feed learnings to product', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Segments ready', daysFromNow: 5 }, { title: 'Campaign done', daysFromNow: 21 } ],
  },
  {
    key: 'support-automation', category: 'Customer Support', Icon: Zap, name: 'Support Automation', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Identify the most repetitive tickets', status: 'todo', priority: 'high' },
      { title: 'Write canned responses', status: 'todo', priority: 'medium' },
      { title: 'Set up routing rules', status: 'todo', priority: 'high' },
      { title: 'Build a simple chatbot flow', status: 'todo', priority: 'medium' },
      { title: 'Test the automations', status: 'todo', priority: 'high' },
      { title: 'Monitor and tune', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Macros live', daysFromNow: 7 }, { title: 'Automation running', daysFromNow: 18 } ],
  },
  {
    key: 'idea-validation', category: 'Startups', Icon: Lightbulb, name: 'Idea Validation', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Write the problem and hypothesis', status: 'todo', priority: 'high' },
      { title: 'Identify the target customer', status: 'todo', priority: 'high' },
      { title: 'Interview 10 potential users', status: 'todo', priority: 'high' },
      { title: 'Build a simple landing test', status: 'todo', priority: 'medium' },
      { title: 'Measure real interest', status: 'todo', priority: 'high' },
      { title: 'Decide pivot or proceed', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Interviews done', daysFromNow: 10 }, { title: 'Go/no-go', daysFromNow: 18 } ],
  },
  {
    key: 'mvp-sprint', category: 'Startups', Icon: Rocket, name: 'MVP Sprint', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define the single core flow', status: 'todo', priority: 'high' },
      { title: 'Cut everything non-essential', status: 'todo', priority: 'high' },
      { title: 'Build the core feature', status: 'todo', priority: 'high' },
      { title: 'Add basic auth and payment', status: 'todo', priority: 'medium' },
      { title: 'Test with a few real users', status: 'todo', priority: 'high' },
      { title: 'Ship to first users', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Scope locked', daysFromNow: 3 }, { title: 'MVP shipped', daysFromNow: 21 } ],
  },
  {
    key: 'pitch-deck', category: 'Startups', Icon: Presentation, name: 'Pitch Deck', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Draft the narrative', status: 'todo', priority: 'high' },
      { title: 'Build problem and solution slides', status: 'todo', priority: 'high' },
      { title: 'Add market and traction', status: 'todo', priority: 'high' },
      { title: 'Add team and the ask', status: 'todo', priority: 'medium' },
      { title: 'Design and polish', status: 'todo', priority: 'medium' },
      { title: 'Rehearse the pitch', status: 'todo', priority: 'high' },
    ],
    milestones: [ { title: 'Draft ready', daysFromNow: 7 }, { title: 'Deck final', daysFromNow: 14 } ],
  },
  {
    key: 'first-10-customers', category: 'Startups', Icon: Users, name: 'First 10 Customers', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List warm leads and networks', status: 'todo', priority: 'high' },
      { title: 'Write a short personal pitch', status: 'todo', priority: 'high' },
      { title: 'Reach out one by one', status: 'todo', priority: 'high' },
      { title: 'Do demos and onboard', status: 'todo', priority: 'high' },
      { title: 'Collect feedback fast', status: 'todo', priority: 'medium' },
      { title: 'Ask for referrals', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Outreach started', daysFromNow: 3 }, { title: '10 signed', daysFromNow: 30 } ],
  },
  {
    key: 'incorporation', category: 'Startups', Icon: Building, name: 'Incorporation & Setup', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Pick the entity type', status: 'todo', priority: 'high' },
      { title: 'Register the company', status: 'todo', priority: 'high' },
      { title: 'Open a business bank account', status: 'todo', priority: 'high' },
      { title: 'Set up accounting', status: 'todo', priority: 'medium' },
      { title: 'Sort founder agreements', status: 'todo', priority: 'high' },
      { title: 'Handle basic legal and tax setup', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Registered', daysFromNow: 14 }, { title: 'Operational', daysFromNow: 30 } ],
  },
  {
    key: 'lesson-plan', category: 'Education', Icon: BookOpen, name: 'Lesson Plan', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define the learning objective', status: 'todo', priority: 'high' },
      { title: 'Outline the lesson flow', status: 'todo', priority: 'high' },
      { title: 'Prepare materials and slides', status: 'todo', priority: 'medium' },
      { title: 'Design an activity or exercise', status: 'todo', priority: 'medium' },
      { title: 'Create an assessment', status: 'todo', priority: 'medium' },
      { title: 'Review and refine', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Outline done', daysFromNow: 3 }, { title: 'Ready to teach', daysFromNow: 7 } ],
  },
  {
    key: 'certification-study', category: 'Education', Icon: Award, name: 'Certification Study', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List all exam domains', status: 'todo', priority: 'high' },
      { title: 'Build a weekly study schedule', status: 'todo', priority: 'high' },
      { title: 'Gather study resources', status: 'todo', priority: 'medium' },
      { title: 'Study in daily blocks', status: 'todo', priority: 'high' },
      { title: 'Take practice exams', status: 'todo', priority: 'high' },
      { title: 'Review weak areas', status: 'todo', priority: 'medium' },
    ],
    milestones: [ { title: 'Halfway', daysFromNow: 21 }, { title: 'Exam', daysFromNow: 40 } ],
  },
  {
    key: 'research-paper', category: 'Education', Icon: FileText, name: 'Research Paper', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define the research question', status: 'todo', priority: 'high' },
      { title: 'Review the literature', status: 'todo', priority: 'high' },
      { title: 'Collect and analyze data', status: 'todo', priority: 'high' },
      { title: 'Write the draft', status: 'todo', priority: 'high' },
      { title: 'Revise with feedback', status: 'todo', priority: 'medium' },
      { title: 'Format and submit', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Draft done', daysFromNow: 30 }, { title: 'Submitted', daysFromNow: 45 } ],
  },
  {
    key: 'bootcamp', category: 'Education', Icon: GraduationCap, name: 'Bootcamp Curriculum', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define outcomes and audience', status: 'todo', priority: 'high' },
      { title: 'Design the week-by-week plan', status: 'todo', priority: 'high' },
      { title: 'Build projects and exercises', status: 'todo', priority: 'high' },
      { title: 'Prepare instructor materials', status: 'todo', priority: 'medium' },
      { title: 'Set up assessments', status: 'todo', priority: 'medium' },
      { title: 'Pilot with a small group', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Curriculum ready', daysFromNow: 14 }, { title: 'Pilot done', daysFromNow: 35 } ],
  },
  {
    key: 'job-search', category: 'Personal & Productivity', Icon: Briefcase, name: 'Job Search', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Update resume and profiles', status: 'todo', priority: 'high' },
      { title: 'Build a target company list', status: 'todo', priority: 'high' },
      { title: 'Tailor applications', status: 'todo', priority: 'high' },
      { title: 'Network and get referrals', status: 'todo', priority: 'medium' },
      { title: 'Prep for interviews', status: 'todo', priority: 'high' },
      { title: 'Track and follow up', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Applications out', daysFromNow: 7 }, { title: 'Interviews', daysFromNow: 21 } ],
  },
  {
    key: 'side-project', category: 'Personal & Productivity', Icon: Rocket, name: 'Side Project', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'Define the goal and scope', status: 'todo', priority: 'high' },
      { title: 'Break it into small milestones', status: 'todo', priority: 'high' },
      { title: 'Set a weekly time budget', status: 'todo', priority: 'medium' },
      { title: 'Build the first version', status: 'todo', priority: 'high' },
      { title: 'Share it for feedback', status: 'todo', priority: 'medium' },
      { title: 'Iterate or ship', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'First version', daysFromNow: 21 }, { title: 'Shipped', daysFromNow: 45 } ],
  },
  {
    key: 'reading-list', category: 'Personal & Productivity', Icon: BookOpen, name: 'Reading List', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List books and articles', status: 'todo', priority: 'medium' },
      { title: 'Prioritize the queue', status: 'todo', priority: 'medium' },
      { title: 'Set a reading schedule', status: 'todo', priority: 'high' },
      { title: 'Take notes as you go', status: 'todo', priority: 'medium' },
      { title: 'Summarize key takeaways', status: 'todo', priority: 'low' },
      { title: 'Apply one idea', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Queue set', daysFromNow: 2 }, { title: 'First book done', daysFromNow: 14 } ],
  },
  {
    key: 'budget-personal', category: 'Personal & Productivity', Icon: Wallet, name: 'Personal Budget', description: '6 tasks · 2 milestones',
    tasks: [
      { title: 'List income and fixed costs', status: 'todo', priority: 'high' },
      { title: 'Track a month of spending', status: 'todo', priority: 'high' },
      { title: 'Categorize the spend', status: 'todo', priority: 'medium' },
      { title: 'Set category limits', status: 'todo', priority: 'high' },
      { title: 'Automate savings', status: 'todo', priority: 'medium' },
      { title: 'Review monthly', status: 'todo', priority: 'low' },
    ],
    milestones: [ { title: 'Baseline tracked', daysFromNow: 30 }, { title: 'Budget set', daysFromNow: 35 } ],
  },
  {
    key: 'wedding-planning', category: 'Personal & Productivity', Icon: Heart, name: 'Wedding Planning', description: '6 tasks · 3 milestones',
    tasks: [
      { title: 'Set budget and guest count', status: 'todo', priority: 'high' },
      { title: 'Book venue and date', status: 'todo', priority: 'high' },
      { title: 'Line up key vendors', status: 'todo', priority: 'high' },
      { title: 'Send invitations', status: 'todo', priority: 'medium' },
      { title: 'Plan the schedule and details', status: 'todo', priority: 'medium' },
      { title: 'Final confirmations', status: 'todo', priority: 'urgent' },
    ],
    milestones: [ { title: 'Venue booked', daysFromNow: 30 }, { title: 'Invites sent', daysFromNow: 90 }, { title: 'Wedding day', daysFromNow: 180 } ],
  },
]

export const CATEGORY_ORDER = ['Business & Sales', 'Marketing', 'Design & Engineering', 'Product Management', 'Content & Media', 'HR & Operations', 'Team Management', 'Remote Teams', 'Finance', 'Customer Support', 'Startups', 'Education', 'Personal & Productivity']


export const CATEGORY_META = {
  'Business & Sales':        { gradient: 'from-blue-600 to-cyan-500',    desc: 'From lead to close - pipelines, outreach, and deals that move.' },
  'Marketing':               { gradient: 'from-fuchsia-500 to-pink-500', desc: 'Launches, campaigns, and content that actually convert.' },
  'Design & Engineering':    { gradient: 'from-indigo-600 to-teal-500',  desc: 'Ship product - from wireframes to bug-free releases.' },
  'Product Management':      { gradient: 'from-slate-700 to-indigo-600', desc: 'Specs, research, and roadmaps that keep teams aligned.' },
  'Content & Media':         { gradient: 'from-purple-600 to-pink-500',  desc: 'Plan, produce, and publish across every channel.' },
  'HR & Operations':         { gradient: 'from-slate-500 to-slate-300',  desc: 'Hire, onboard, and run the people side of the business.' },
  'Team Management':         { gradient: 'from-violet-700 to-rose-600',  desc: 'Coordinate people, meetings, and the work between them.' },
  'Remote Teams':            { gradient: 'from-pink-500 to-amber-400',   desc: 'Keep a distributed team connected, aligned, and shipping.' },
  'Finance':                 { gradient: 'from-emerald-600 to-teal-500', desc: 'Budgets, close, and fundraising without spreadsheet chaos.' },
  'Customer Support':        { gradient: 'from-slate-600 to-slate-400',  desc: 'Triage tickets and turn feedback into a better product.' },
  'Startups':                { gradient: 'from-sky-400 to-blue-500',     desc: 'Go from idea to traction with founder-ready playbooks.' },
  'Education':               { gradient: 'from-blue-500 to-indigo-500',  desc: 'Build courses, run cohorts, and plan your own learning.' },
  'Personal & Productivity': { gradient: 'from-amber-500 to-orange-500', desc: 'Organize your goals, week, and life outside work.' },
}
